logging:
  level:
    root: info
server:
  port: 8080
spring:
  jpa:
    database: mysql
    hibernate:
      ddl-auto: none
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.11.99:3306/equipment?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowMultiQueries=true&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: equipment
    password: 123456
  elasticsearch:
    uris: http://localhost:9200
